### ISSUE TITLE
Add support for ebay providers

### ISSUE THREAD

**Issue by carlosflorencio** [hdnpt/geartrack#16]
@BanaipePT 
A meu ver acho que seria uma excelente melhoria dado a quantidade de compras que existem usando a plataforma do eBay.

Reconheço que a própria plataforma já tem um mecanismo próprio mas que nem sempre funciona e apenas fornece informações básicas.

Formato Geral

HKxxxxxxxxxPY
HKxxxxxxxxxAM
UAxxxxxxxxxYP
ID Para Testes

HK694459332PY
HK05341163AM
UA846098317YP

**Comment by rcacheira** [comment]
UA846098317YP track por Yanwen o que mostra que temos de corrigir o yanwen aparecem linha entre o origin country e o destiny country

**Comment by carlosflorencio** [comment]
One more tracking number from ebay:
UPAAA000000218364455

U....YP - Done! Live!

**Comment by carlosflorencio** [comment]
ID18050571940625CN
Another one from ebay

**Comment by carlosflorencio** [comment]
OZ018709285PY

Another one

**Comment by carlosflorencio** [comment]
http://track.winit.com.cn/tracking/Index/result

New one: ID18050634174840CN

**Comment by rcacheira** [comment]
Done

**Comment by carlosflorencio** [comment]
HK694459332PY
HK05341163AM -> https://www.sendfromchina.com/track/track/track
OZ018709285PY:
https://www.17track.net/en/track?nums=OZ018709285PY
http://xoms.4px.com/home/track/home_index?trackNums=&locale=

UPAAA000000218364455:
https://parceltracking.pb.com/app/#/dashboard/UPAAA000000218364455

Are not done yet.

**Comment by carlosflorencio** [comment]
HK694531035PY
YF300536891 - > Yanwen already made!

**Comment by carlosflorencio** [comment]
New ID:
EYX170428AUW000163
http://www.chukou1.com/LogistictsTrack.aspx?trackNo=EYX170428AUW000163#

**Comment by carlosflorencio** [comment]
New ID:
BZ013283414CN
China EMS ePacket

**Comment by carlosflorencio** [comment]
New one: (eBay > Royal Mail)
https://gls-group.eu/EU/en/parcel-tracking?match=RS848042845GB

**Comment by carlosflorencio** [comment]
New: XYGPY8803151881YQ

**Comment by carlosflorencio** [comment]
New one:
https://www.royalmail.com/track-your-item?trackNumber=RU936061244GB

widely used by uk sellers
