### ISSUE TITLE
Cainiao asks for the tracking method before showing some information

### ISSUE THREAD

**Issue by carlosflorencio** [hdnpt/geartrack#22]
Some ids are showing blank cainiao info on the geartrack website.

That's because it was necessary to choose the correct method (Malasya pos instead of others) in the cainiao website before it shows the correct info.

Affected id: RC104712375MY
After choosing, the info on cainiao was displayed.

**Comment by carlosflorencio** [comment]
![2017-04-12_15-21-30](https://cloud.githubusercontent.com/assets/1500881/24962926/2a94d974-1f95-11e7-8606-7bb45c66f1d1.png)

Another option to get the info:
http://www.pos.com.my/postal-services/quick-access/?track-trace

More info & possible solution:
https://gist.github.com/iamfreee/292dd223a86576d5293ae07a596ace16

**Comment by carlosflorencio** [comment]
Another popup to choose the destination country:
![2017-04-12_15-35-06](https://cloud.githubusercontent.com/assets/1500881/24963671/26ef71f6-1f97-11e7-903e-2ad93bf7ece4.png)

(geartrack doesnt get any states)

https://gist.github.com/iamfreee/25e558dd9e1a5844df99ef9e775da84c

**Comment by carlosflorencio** [comment]
A temporary solution:

When the geartrack returns 0 states, we show a link to cainiao so the person can choose the right options.
Website cache has to be aware of this and do not cache the response until the cainiao returns the states.

**Comment by rcacheira** [comment]
We can parse the options and ask to select the option on geartrack website.
This avoids the user to go to another website.

**Comment by rcacheira** [comment]
Other way is to try to parse all the options until we get any good response. This way the user doesn't need to select anything.

**Comment by rcacheira** [comment]
Getting the info directly from malaysia pos site
