### ISSUE TITLE
Support Seur

### ISSUE THREAD

**Issue by tiagoboldt** [hdnpt/geartrack#67]
Hey, 

Great project. I would suggest growing it outside the gearbest domain by supporting additional transportation companies. Specifically, SEUR would be very useful for me.

**Comment by carlosflorencio** [comment]
Yep, we will support carriers instead of stores.
(we do that now, but with some emphasis on Gearbest carriers)

We are waiting for an active Seur id to implement, because Gearbest is testing Seur at the moment.

If you have a valid id, post it here or send to us by our Facebook page.  😃

**Comment by tiagoboldt** [comment]
Valid SEUR tracking code: 9340160961

**Comment by valascus** [comment]
Other Seur Tracking code:

SEU230009036281

**Comment by carlosflorencio** [comment]
@valascus 
Just associated Seur tracker with that id format. 

Merry Christmas 🎅
